<?php

/**
 * @file
 * Provides a Libraries module based loader for the Paymill API.
 */

/**
 * Implements hook_libraries_info().
 */
function paymill_api_libraries_info() {
  $libraries = array();

  $libraries['paymill'] = array(
    'name' => 'Paymill',
    'vendor' => 'http://www.paymill.com/',
    'download_url' => 'https://github.com/Paymill/Paymill-PHP/archive/master.zip',
    'path' => 'lib/Services/Paymill',
    'version arguments' => array(
      'file' => 'lib/Services/Paymill/Apiclient/Curl.php',
      'pattern' => '@Paymill-php/([0-9\.]+)@',
      'lines' => 40,
    ),
    'files' => array(
      'php' => array(
        'Clients.php',
        'Coupons.php',
        'Exception.php',
        'Offers.php',
        'Payments.php',
        'Refunds.php',
        'Subscriptions.php',
        'Transactions.php',
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_requirements().
 */
function paymill_api_requirements($phase) {
  $requirements = array();

  if ($phase == 'runtime') {
    // Check Paymill library is installed.
    $library = libraries_detect('paymill');
    if (!empty($library['installed'])) {
      $value = $library['version'];
      $description = NULL;
      $severity = REQUIREMENT_OK;
    }
	else {
      $value = t('Not installed');
      $description = $library['error message'];
      $severity = REQUIREMENT_ERROR;
    }
    $requirements['paymill_library'] = array(
      'title' => t('Paymill library'),
      'value' => $value,
      'description' => $description,
      'severity' => $severity,
    );

    // Check cURL is installed.
    $curl = function_exists('curl_init');
    $requirements['paymill_curl'] = array(
      'title' => t('Paymill cURL support'),
      'value' => $curl ? t('cURL extension enabled') : t('cURL extension is not installed/enabled'),
      'description' => NULL,
      'severity' => $curl ? REQUIREMENT_OK : REQUIREMENT_ERROR,
    );

    // Check JSON is installed.
    $curl = function_exists('json_decode');
    $requirements['paymill_json'] = array(
      'title' => t('Paymill JSON support'),
      'value' => $curl ? t('JSON extension enabled') : t('JSON extension is not installed/enabled'),
      'description' => NULL,
      'severity' => $curl ? REQUIREMENT_OK : REQUIREMENT_ERROR,
    );
  }

  return $requirements;
}
